### ISSUE TITLE
can not run the code

### ISSUE THREAD

**Issue by 123qwe-ux** [hyintell/CHBias#1]
Hello, the author, there are many path problems in the project, which can not run. Is your project complete?

**Comment by 123qwe-ux** [comment]
Traceback (most recent call last):
  File "/mnt/nlp/zwx/chbias/src/../examples/language-modeling/debias_lm_grid.py", line 31, in <module>
    from transformers import (
  File "/home/work/anaconda3/envs/chbias/lib/python3.9/site-packages/transformers-3.3.0-py3.9.egg/transformers/__init__.py", line 65, in <module>
    from .data import (
ModuleNotFoundError: No module named 'transformers.data'
